name: Test pip install
on:
  workflow_dispatch: # Allow manual triggers
    inputs:
      mct_quantizers_version:
        description: 'MCT Quantizers version'
        required: true
        default: 'v1.1.0'
      python_version:
        description: 'Python version'
        required: false
        default: '3.10'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: ${{  inputs.python_version  }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install tensorflow tensorflow-model-optimization
      - name: Build WHL file
        run: |
          version=$(python -c 'import mct_quantizers; print(mct_quantizers.__version__)')
          now=$(date +'%Y%m%d-%H%M%S')
          echo "nightly_version=$version.$now" >> $GITHUB_ENV

